# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline on UK Biobank

input_format: "plink"

# Prerequisite
list_of_plink_files: "ukb_paths/eur/eur_plink_file_list.txt"
list_of_loco_files: "ukb_paths/eur/eur_loco_file_list.txt"
list_of_regenie_annotation_files: "ukb_paths/eur/eur_annotation_file_list.txt"
list_of_regenie_setlist_files: "ukb_paths/eur/eur_setlist_file_list.txt"
keep: "snakemake_eur/mtx/brava_EUR_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
phenotype_file: "snakemake_eur/phenotypes/ukb.standing_height.20250508.tsv.gz"
covariate_file: "snakemake_eur/phenotypes/ukb_brava_default_covariates.20250508.tsv.gz"

# Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "gene_phenotype_pairs_051125.csv"
protein_coding_region_bed: "data/protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "pilot_phenotypes.json"
covariate_cols: "age,age2,age_sex,age2_sex,sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10"
categorical_covariate_cols: "sex"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense_or_protein_altering,other_missense_or_protein_altering,synonymous,pLoF:damaging_missense_or_protein_altering,pLoF:damaging_missense_or_protein_altering:other_missense_or_protein_altering:synonymous"
conditioning_pvalue: 0.00001

# SAIGE versions for filetypes
saige_vcf_version: "1.3.6"
saige_plink_version: "1.3.6"
saige_pgen_version: "1.5.0"
