# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline on AoU

input_format: "plink"  # or "plink"

# Prerequisite
list_of_vcf_files: "aou_paths/sas/sas_vcf_file_list.txt"
list_of_model_files: "aou_paths/sas/sas_model_file_list.txt"
list_of_variance_ratio_files: "aou_paths/sas/sas_variance_file_list.txt"
sparse_matrix: "snakemake_sas/mtx/allofus_array_sas_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
list_of_group_files: "aou_paths/sas/sas_group_file_list.txt"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
# gene_trait_pairs_to_test: "gene_phenotype_pairs_101025.csv"
gene_trait_pairs_to_test: "gene_phenotype_pairs_051125.csv"
gene_trait_pairs_to_test_with_conditioning_variants: "gene_phenotype_pairs_with_conditioning_variants_251125_SAS.tsv"
protein_coding_region_bed: "protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "pilot_phenotypes.json"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense,other_missense,synonymous,pLoF:damaging_missense,pLoF:damaging_missense:other_missense:synonymous"
use_null_var_ratio: false
conditioning_pvalue: 0.00001

# SAIGE versions for filetypes
saige_vcf_version: "1.3.6"
saige_plink_version: "1.3.6"
saige_pgen_version: "1.5.0"
